server:
  port: 18086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5              #声明thymeleaf使用非严格的html。
    servlet:
      content-type: text/html
  application:
    name: search-web
  main:
    allow-bean-definition-overriding: true