server:
  port: 18083
spring:
  application:
    name: canal
  redis:
    host: 192.168.0.167
    port: 6379
  #rabbitmq配置
  rabbitmq:
    host: 192.168.0.167
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  client:
    instances:
      #指定实例
      example:
        host: 192.168.0.167
        port: 11111