server:
  port: 18090
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.0.167
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  #应用ID
  appid: wx8397f8696b538317
  #商户ID
  partner: 1473426802
  #秘钥
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付回调地址
  notifyurl: http://59n48d.natappfree.cc/weixin/pay/notify/url

#位置支付交换机和队列
mq:
  pay:
    exchange:   #消息发送到哪个交换机
      order: exchange.order
      seckillOrder: exchange.seckillOrder
    queue:    #队列名称
      order: queue.order
      seckillOrder: queue.seckillOrder
    routing:    #路由名称
      key: queue.order
      seckillKey: queue.seckillOrder