server:
  port: 18087
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5              #声明thymeleaf使用非严格的html。
    servlet:
      content-type: text/html
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
  #rabbitmq配置
  rabbitmq:
    host: 192.168.0.167
    port: 5672
    username: guest
    password: guest

# 生成静态页的位置
pagepath: E:/ideaspace/cg-v3/parent/web/web-item/src/main/resources/templates/items/